// Generated by gencpp from file faceReg/facePose.msg
// DO NOT EDIT!


#ifndef FACEREG_MESSAGE_FACEPOSE_H
#define FACEREG_MESSAGE_FACEPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace faceReg
{
template <class ContainerAllocator>
struct facePose_
{
  typedef facePose_<ContainerAllocator> Type;

  facePose_()
    : header()
    , trans_x(0.0)
    , trans_y(0.0)
    , trans_z(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)  {
    }
  facePose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , trans_x(0.0)
    , trans_y(0.0)
    , trans_z(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _trans_x_type;
  _trans_x_type trans_x;

   typedef double _trans_y_type;
  _trans_y_type trans_y;

   typedef double _trans_z_type;
  _trans_z_type trans_z;

   typedef double _rot_x_type;
  _rot_x_type rot_x;

   typedef double _rot_y_type;
  _rot_y_type rot_y;

   typedef double _rot_z_type;
  _rot_z_type rot_z;




  typedef boost::shared_ptr< ::faceReg::facePose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::faceReg::facePose_<ContainerAllocator> const> ConstPtr;

}; // struct facePose_

typedef ::faceReg::facePose_<std::allocator<void> > facePose;

typedef boost::shared_ptr< ::faceReg::facePose > facePosePtr;
typedef boost::shared_ptr< ::faceReg::facePose const> facePoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::faceReg::facePose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::faceReg::facePose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace faceReg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'faceReg': ['/home/weety/tart5/src/faceReg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::faceReg::facePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::faceReg::facePose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::faceReg::facePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::faceReg::facePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::faceReg::facePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::faceReg::facePose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::faceReg::facePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efb58ddc3c5f275bf54bdee14c47103a";
  }

  static const char* value(const ::faceReg::facePose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefb58ddc3c5f275bULL;
  static const uint64_t static_value2 = 0xf54bdee14c47103aULL;
};

template<class ContainerAllocator>
struct DataType< ::faceReg::facePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "faceReg/facePose";
  }

  static const char* value(const ::faceReg::facePose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::faceReg::facePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 trans_x\n\
float64 trans_y\n\
float64 trans_z\n\
float64 rot_x\n\
float64 rot_y\n\
float64 rot_z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::faceReg::facePose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::faceReg::facePose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.trans_x);
      stream.next(m.trans_y);
      stream.next(m.trans_z);
      stream.next(m.rot_x);
      stream.next(m.rot_y);
      stream.next(m.rot_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct facePose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::faceReg::facePose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::faceReg::facePose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "trans_x: ";
    Printer<double>::stream(s, indent + "  ", v.trans_x);
    s << indent << "trans_y: ";
    Printer<double>::stream(s, indent + "  ", v.trans_y);
    s << indent << "trans_z: ";
    Printer<double>::stream(s, indent + "  ", v.trans_z);
    s << indent << "rot_x: ";
    Printer<double>::stream(s, indent + "  ", v.rot_x);
    s << indent << "rot_y: ";
    Printer<double>::stream(s, indent + "  ", v.rot_y);
    s << indent << "rot_z: ";
    Printer<double>::stream(s, indent + "  ", v.rot_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACEREG_MESSAGE_FACEPOSE_H
